FROM docker.io/library/alpine:latest@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b

COPY ./pal /usr/bin/
COPY ./entrypoint.sh ./localhost.key ./localhost.pem /etc/pal/

RUN apk update && \
    apk add --no-cache curl \
        jq \
        tzdata \
        gcompat \
        ca-certificates && \
    rm -rf /var/cache/apk/*&& \
    mkdir -p /etc/pal/pal.db /etc/pal/actions /pal/upload && \
    addgroup --gid 1000 --system pal && \
    adduser --uid 1000 --system --ingroup pal --home /pal --shell /sbin/nologin pal && \
    chown -Rf pal:pal /etc/pal && \
    chown -Rf pal:pal /etc/pal/pal.db /pal && \
    chmod -f 0640 /etc/pal/localhost.* && \
    chmod -f 0755 /usr/bin/pal /etc/pal/*.sh
    
USER pal

WORKDIR /pal

EXPOSE 8443

HEALTHCHECK --interval=60s --timeout=15s --retries=2 \
  CMD /usr/bin/pal -s -c /etc/pal/pal.yml || exit 1

ENTRYPOINT ["/etc/pal/entrypoint.sh"]
