FROM docker.io/library/alpine:latest@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

COPY ./pal /pal/
COPY ./entrypoint.sh ./localhost.key ./localhost.pem /etc/pal/

RUN apk update && \
    apk add --no-cache curl \
        jq \
        tzdata \
        ca-certificates && \
    rm -rf /var/cache/apk/*&& \
    mkdir -p /etc/pal/pal.db /etc/pal/actions /pal/upload && \
    addgroup --gid 1000 --system pal && \
    adduser --uid 1000 --system --ingroup pal --home /pal --shell /sbin/nologin pal && \
    chown -Rf pal:pal /pal /etc/pal && \
    chmod -f 0755 /etc/pal/*.sh /pal/pal
    
USER pal

WORKDIR /pal

EXPOSE 8443
    
ENTRYPOINT ["/etc/pal/entrypoint.sh"]
