FROM alpine:latest@sha256:21dc6063fd678b478f57c0e13f47560d0ea4eeba26dfc947b2a4f81f686b9f45

COPY ./pal /pal/
COPY ./entrypoint.sh ./localhost.key ./localhost.pem /etc/pal/

WORKDIR /pal

RUN apk update && \
    apk add --no-cache curl \
        jq \
        tzdata \
        ca-certificates && \
    rm -rf /var/cache/apk/*&& \
    mkdir -p /etc/pal/pal.db /etc/pal/actions /pal/upload && \
    addgroup --gid 101010 --system pal && \
    adduser --uid 101010 --system --ingroup pal --home /pal --shell /sbin/nologin pal && \
    chown -Rf pal:pal /pal /etc/pal
    
USER pal
    
EXPOSE 8443
    
ENTRYPOINT ["/etc/pal/entrypoint.sh"]
